In [1]:
import numpy as np

import pandas as pd

In [2]:
#pandas provides two types of classes for handling data
 #1.Series: a one-dimensional labeled array holding data of any type
            #such as integers, strings, Python objects etc.

 #2.DataFrame: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

In [3]:
#Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). 
#The axis labels are collectively referred to as the index. The basic method to create a Series is to call

#s = pd.Series(data, index=index)

In [4]:
s= pd.Series([1,3, 5, np.nan, 6, 8])

print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
s= pd.Series(np.random.rand(5), index=["a","b","c","d","e"])
print(s)

a    0.732006
b    0.100576
c    0.569452
d    0.495348
e    0.341272
dtype: float64

In [6]:
d = {"b": 1, "a": 0, "c": 2}
pd.Series(d)

b    1
a    0
c    2
dtype: int64

In [7]:
dates = pd.date_range("20260101", periods=6)
dates

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06'],
              dtype='datetime64[ns]', freq='D')

In [8]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df)

                   A         B         C         D
2026-01-01 -0.026497 -1.050630 -0.159357  0.405202
2026-01-02  1.203786 -0.095479 -1.743286  0.216495
2026-01-03  0.608752  0.654561  0.209684  0.425139
2026-01-04  0.219762 -0.796078 -1.457209  1.283422
2026-01-05  1.577619 -1.615634 -0.166195 -0.522778
2026-01-06  0.312017 -1.244827 -0.970908  0.752010

In [9]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20260102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype= "int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo"
    }
)

print(df2)

     A          B    C  D      E    F
0  1.0 2026-01-02  1.0  3   test  foo
1  1.0 2026-01-02  1.0  3  train  foo
2  1.0 2026-01-02  1.0  3   test  foo
3  1.0 2026-01-02  1.0  3  train  foo

In [10]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [11]:
df2.head(2)

     A          B    C  D      E    F
0  1.0 2026-01-02  1.0  3   test  foo
1  1.0 2026-01-02  1.0  3  train  foo

In [241]:
df2.tail(2)

     A          B    C  D      E    F
2  1.0 2026-01-02  1.0  3   test  foo
3  1.0 2026-01-02  1.0  3  train  foo

In [242]:
df2.index

Index([0, 1, 2, 3], dtype='int64')

In [243]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [244]:
df.to_numpy()

array([[ 0.28539792, -1.53600514, -0.25598601,  0.0450391 ],
       [ 0.31943709,  0.23080735,  1.14031162,  0.16248379],
       [ 0.24615935,  1.43188178,  0.20561443, -0.41502767],
       [ 1.55761268,  0.62789104, -1.80575467,  0.05221959],
       [ 0.08848292, -0.70642714,  2.36570194,  0.59501384],
       [-0.36685813, -0.85222362,  1.62780927,  0.22104627]])

In [245]:
# NumPy arrays have one dtype for the entire array while pandas DataFrames have one dtype per column. 
#    When you call DataFrame.to_numpy(), pandas will find the NumPy dtype that can hold all of the dtypes in the DataFrame. 
#        If the common data type is object, DataFrame.to_numpy() will require copying data.

In [246]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [247]:
df2.to_numpy()

array([[1.0, Timestamp('2026-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2026-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2026-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2026-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [248]:
#describe() shows a quick statistic summary of your data:

df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.355039 -0.134013  0.546283  0.110129
std    0.641302  1.093132  1.491618  0.326661
min   -0.366858 -1.536005 -1.805755 -0.415028
25%    0.127902 -0.815775 -0.140586  0.046834
50%    0.265779 -0.237810  0.672963  0.107352
75%    0.310927  0.528620  1.505935  0.206406
max    1.557613  1.431882  2.365702  0.595014

In [249]:
#Transposing your data:

df.T

   2026-01-01  2026-01-02  2026-01-03  2026-01-04  2026-01-05  2026-01-06
A    0.285398    0.319437    0.246159    1.557613    0.088483   -0.366858
B   -1.536005    0.230807    1.431882    0.627891   -0.706427   -0.852224
C   -0.255986    1.140312    0.205614   -1.805755    2.365702    1.627809
D    0.045039    0.162484   -0.415028    0.052220    0.595014    0.221046

In [250]:
#DataFrame.sort_index() sorts by an axis:

df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2026-01-01  0.045039 -0.255986 -1.536005  0.285398
2026-01-02  0.162484  1.140312  0.230807  0.319437
2026-01-03 -0.415028  0.205614  1.431882  0.246159
2026-01-04  0.052220 -1.805755  0.627891  1.557613
2026-01-05  0.595014  2.365702 -0.706427  0.088483
2026-01-06  0.221046  1.627809 -0.852224 -0.366858

In [251]:
df.sort_values(by="B")

                   A         B         C         D
2026-01-01  0.285398 -1.536005 -0.255986  0.045039
2026-01-06 -0.366858 -0.852224  1.627809  0.221046
2026-01-05  0.088483 -0.706427  2.365702  0.595014
2026-01-02  0.319437  0.230807  1.140312  0.162484
2026-01-04  1.557613  0.627891 -1.805755  0.052220
2026-01-03  0.246159  1.431882  0.205614 -0.415028

In [252]:
df["A"]

2026-01-01    0.285398
2026-01-02    0.319437
2026-01-03    0.246159
2026-01-04    1.557613
2026-01-05    0.088483
2026-01-06   -0.366858
Freq: D, Name: A, dtype: float64

In [253]:
df.A

2026-01-01    0.285398
2026-01-02    0.319437
2026-01-03    0.246159
2026-01-04    1.557613
2026-01-05    0.088483
2026-01-06   -0.366858
Freq: D, Name: A, dtype: float64

In [254]:
df[["B","A"]]

                   B         A
2026-01-01 -1.536005  0.285398
2026-01-02  0.230807  0.319437
2026-01-03  1.431882  0.246159
2026-01-04  0.627891  1.557613
2026-01-05 -0.706427  0.088483
2026-01-06 -0.852224 -0.366858

In [255]:
df[0:3]

                   A         B         C         D
2026-01-01  0.285398 -1.536005 -0.255986  0.045039
2026-01-02  0.319437  0.230807  1.140312  0.162484
2026-01-03  0.246159  1.431882  0.205614 -0.415028

In [256]:
df[0:]

                   A         B         C         D
2026-01-01  0.285398 -1.536005 -0.255986  0.045039
2026-01-02  0.319437  0.230807  1.140312  0.162484
2026-01-03  0.246159  1.431882  0.205614 -0.415028
2026-01-04  1.557613  0.627891 -1.805755  0.052220
2026-01-05  0.088483 -0.706427  2.365702  0.595014
2026-01-06 -0.366858 -0.852224  1.627809  0.221046

In [257]:
df["20260102":"20260104"]

                   A         B         C         D
2026-01-02  0.319437  0.230807  1.140312  0.162484
2026-01-03  0.246159  1.431882  0.205614 -0.415028
2026-01-04  1.557613  0.627891 -1.805755  0.052220

In [258]:
#Selection by label
#pandas.DataFrame.loc - Access a group of rows and columns by label(s) or a boolean array.\
#.loc[] is primarily label based, but may also be used with a boolean array.
df.loc[dates[0]]

A    0.285398
B   -1.536005
C   -0.255986
D    0.045039
Name: 2026-01-01 00:00:00, dtype: float64

In [259]:
df.loc[:, ["A", "B"]]

                   A         B
2026-01-01  0.285398 -1.536005
2026-01-02  0.319437  0.230807
2026-01-03  0.246159  1.431882
2026-01-04  1.557613  0.627891
2026-01-05  0.088483 -0.706427
2026-01-06 -0.366858 -0.852224

In [260]:
df.loc["20260102":"20260104", ["A", "B"]]

                   A         B
2026-01-02  0.319437  0.230807
2026-01-03  0.246159  1.431882
2026-01-04  1.557613  0.627891

In [261]:
df.loc[dates[0], "A"]

np.float64(0.28539791894591526)

In [262]:
#Selection by position

#DataFrame.iloc   -  Access group of rows and columns by integer position(s).

df.iloc[3]

A    1.557613
B    0.627891
C   -1.805755
D    0.052220
Name: 2026-01-04 00:00:00, dtype: float64

In [263]:
df.iloc[3:5, 0:2]

                   A         B
2026-01-04  1.557613  0.627891
2026-01-05  0.088483 -0.706427

In [264]:
df.iloc[[1, 2, 4], [0, 2]]

                   A         C
2026-01-02  0.319437  1.140312
2026-01-03  0.246159  0.205614
2026-01-05  0.088483  2.365702

In [265]:
df.iloc[:, 1:3]

                   B         C
2026-01-01 -1.536005 -0.255986
2026-01-02  0.230807  1.140312
2026-01-03  1.431882  0.205614
2026-01-04  0.627891 -1.805755
2026-01-05 -0.706427  2.365702
2026-01-06 -0.852224  1.627809

In [266]:
df.iloc[1, 1]

np.float64(0.23080734540751913)

In [267]:
#Boolean indexing

# Select rows where df.A is greater than 0

df[df["A"]>0]

                   A         B         C         D
2026-01-01  0.285398 -1.536005 -0.255986  0.045039
2026-01-02  0.319437  0.230807  1.140312  0.162484
2026-01-03  0.246159  1.431882  0.205614 -0.415028
2026-01-04  1.557613  0.627891 -1.805755  0.052220
2026-01-05  0.088483 -0.706427  2.365702  0.595014

In [268]:
#Selecting values from a DataFrame where a boolean condition is met:
df[df > 0]

                   A         B         C         D
2026-01-01  0.285398       NaN       NaN  0.045039
2026-01-02  0.319437  0.230807  1.140312  0.162484
2026-01-03  0.246159  1.431882  0.205614       NaN
2026-01-04  1.557613  0.627891       NaN  0.052220
2026-01-05  0.088483       NaN  2.365702  0.595014
2026-01-06       NaN       NaN  1.627809  0.221046

In [269]:
df3 = df.copy()

df3["E"] = ["one", "one", "two", "three", "four", "three"]

df3

                   A         B         C         D      E
2026-01-01  0.285398 -1.536005 -0.255986  0.045039    one
2026-01-02  0.319437  0.230807  1.140312  0.162484    one
2026-01-03  0.246159  1.431882  0.205614 -0.415028    two
2026-01-04  1.557613  0.627891 -1.805755  0.052220  three
2026-01-05  0.088483 -0.706427  2.365702  0.595014   four
2026-01-06 -0.366858 -0.852224  1.627809  0.221046  three

In [270]:
df3[df3["E"].isin([ "two", "four"])]

                   A         B         C         D     E
2026-01-03  0.246159  1.431882  0.205614 -0.415028   two
2026-01-05  0.088483 -0.706427  2.365702  0.595014  four

In [271]:
#Setting
#Setting a new column automatically aligns the data by the indexes:

s1 = pd.Series(
    [1,2,3,4,5,6], 
    index = pd.date_range("20230102", periods=6))

print(s1)

2023-01-02    1
2023-01-03    2
2023-01-04    3
2023-01-05    4
2023-01-06    5
2023-01-07    6
Freq: D, dtype: int64

In [272]:
df.at[dates[0], "A"]

np.float64(0.28539791894591526)

In [273]:
df.iat[0, 1] = 0

In [274]:
 df.loc[:, "D"] = np.array([5] * len(df))

In [275]:
#A where operation with setting:

df2 = df.copy()

df4 = df2[df2 > 0] = -df2

df4

                   A         B         C    D
2026-01-01 -0.285398 -0.000000  0.255986 -5.0
2026-01-02 -0.319437 -0.230807 -1.140312 -5.0
2026-01-03 -0.246159 -1.431882 -0.205614 -5.0
2026-01-04 -1.557613 -0.627891  1.805755 -5.0
2026-01-05 -0.088483  0.706427 -2.365702 -5.0
2026-01-06  0.366858  0.852224 -1.627809 -5.0

In [276]:
#Missing data

In [277]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])

df1.loc[dates[0] : dates[1], "E"] = 1

df1

                   A         B         C    D    E
2026-01-01  0.285398  0.000000 -0.255986  5.0  1.0
2026-01-02  0.319437  0.230807  1.140312  5.0  1.0
2026-01-03  0.246159  1.431882  0.205614  5.0  NaN
2026-01-04  1.557613  0.627891 -1.805755  5.0  NaN

In [278]:
#DataFrame.dropna() drops any rows that have missing data:

df1.dropna(how="any")

                   A         B         C    D    E
2026-01-01  0.285398  0.000000 -0.255986  5.0  1.0
2026-01-02  0.319437  0.230807  1.140312  5.0  1.0

In [279]:
#DataFrame.fillna() fills missing data:

df1.fillna(value=5)

                   A         B         C    D    E
2026-01-01  0.285398  0.000000 -0.255986  5.0  1.0
2026-01-02  0.319437  0.230807  1.140312  5.0  1.0
2026-01-03  0.246159  1.431882  0.205614  5.0  5.0
2026-01-04  1.557613  0.627891 -1.805755  5.0  5.0

In [280]:
#isna() gets the boolean mask where values are nan

pd.isna(df1)

                A      B      C      D      E
2026-01-01  False  False  False  False  False
2026-01-02  False  False  False  False  False
2026-01-03  False  False  False  False   True
2026-01-04  False  False  False  False   True

In [281]:
#Calculate the mean value for each column:
df.mean()

A    0.355039
B    0.121988
C    0.546283
D    5.000000
dtype: float64

In [282]:
#Calculate the mean value for each row:

df.mean(axis=1)

2026-01-01    1.257353
2026-01-02    1.672639
2026-01-03    1.720914
2026-01-04    1.344937
2026-01-05    1.686939
2026-01-06    1.352182
Freq: D, dtype: float64

In [283]:
df = pd.DataFrame(np.random.randn(10, 4))
df

          0         1         2         3
0 -0.489155  0.522571  0.702029  0.383731
1  0.139291  0.237963  1.804297 -1.274581
2 -1.049122  1.461112  1.661759 -0.873147
3  1.624113 -1.862824  0.497609  1.048875
4 -1.565210 -1.181481 -1.519678  0.083398
5 -0.034471  0.130438 -1.554200  0.062391
6 -1.569156 -2.208763 -1.906509 -0.314851
7 -0.785188  2.100163  0.118613  0.708486
8 -0.429842  0.609535 -1.218010  0.961914
9  0.334047  0.497665 -0.974744 -0.354053

In [284]:
pieces = [df[:3], df[3:7], df[7:]]
pieces

[          0         1         2         3
 0 -0.489155  0.522571  0.702029  0.383731
 1  0.139291  0.237963  1.804297 -1.274581
 2 -1.049122  1.461112  1.661759 -0.873147,
           0         1         2         3
 3  1.624113 -1.862824  0.497609  1.048875
 4 -1.565210 -1.181481 -1.519678  0.083398
 5 -0.034471  0.130438 -1.554200  0.062391
 6 -1.569156 -2.208763 -1.906509 -0.314851,
           0         1         2         3
 7 -0.785188  2.100163  0.118613  0.708486
 8 -0.429842  0.609535 -1.218010  0.961914
 9  0.334047  0.497665 -0.974744 -0.354053]

In [285]:
pd.concat(pieces)

          0         1         2         3
0 -0.489155  0.522571  0.702029  0.383731
1  0.139291  0.237963  1.804297 -1.274581
2 -1.049122  1.461112  1.661759 -0.873147
3  1.624113 -1.862824  0.497609  1.048875
4 -1.565210 -1.181481 -1.519678  0.083398
5 -0.034471  0.130438 -1.554200  0.062391
6 -1.569156 -2.208763 -1.906509 -0.314851
7 -0.785188  2.100163  0.118613  0.708486
8 -0.429842  0.609535 -1.218010  0.961914
9  0.334047  0.497665 -0.974744 -0.354053

In [286]:
left = pd.DataFrame({"key": ["foo","bar"], "Ival": [1,2]})
right = pd.DataFrame({"key": ["foo", "bar"], "rval": [4, 5]})
right

   key  rval
0  foo     4
1  bar     5

In [287]:
left

   key  Ival
0  foo     1
1  bar     2

In [288]:
pd.merge(left, right, on="key")

   key  Ival  rval
0  foo     1     4
1  bar     2     5

In [289]:
#Grouping

df = pd.DataFrame(
    {
       "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
       "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
       "C": np.random.randn(8),
       "D": np.random.randn(8)
    }
                 )

df

     A      B         C         D
0  foo    one  1.588177  0.966110
1  bar    one  2.122675  0.426536
2  foo    two -0.074930  0.513969
3  bar  three -0.963063 -0.070164
4  foo    two -0.928428 -1.828076
5  bar    two -1.304092  0.033002
6  foo    one  0.785343 -0.070143
7  foo  three  1.828839 -0.187565

In [290]:
df.groupby("A")[["C", "D"]].sum()

            C         D
A
bar -0.144479  0.389373
foo  3.199001 -0.605705

In [291]:
df.groupby(["A", "B"]).sum()

                  C         D
A   B
bar one    2.122675  0.426536
    three -0.963063 -0.070164
    two   -1.304092  0.033002
foo one    2.373520  0.895967
    three  1.828839 -0.187565
    two   -1.003358 -1.314107

In [292]:
#Reshaping
#Hierarchical indexing (MultiIndex)

In [293]:
arrays = [
   ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
   ["one", "two", "one", "two", "one", "two", "one", "two"],
]

arrays

[['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
 ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]

In [297]:
index = pd.MultiIndex.from_arrays(arrays, names = ["first", "second"])

df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=["A", "B"])

df2 =  df[:]

df2

                     A         B
first second
bar   one    -1.427343  0.434162
      two    -1.095679  0.028600
baz   one     1.692814  0.028645
      two     0.403866 -0.460692
foo   one    -0.751738  0.450839
      two    -0.689729  0.712863
qux   one    -0.667461 -0.240495
      two     0.173548 -0.653918

In [298]:
stacked = df2.stack()
stacked

first  second
bar    one     A   -1.427343
               B    0.434162
       two     A   -1.095679
               B    0.028600
baz    one     A    1.692814
               B    0.028645
       two     A    0.403866
               B   -0.460692
foo    one     A   -0.751738
               B    0.450839
       two     A   -0.689729
               B    0.712863
qux    one     A   -0.667461
               B   -0.240495
       two     A    0.173548
               B   -0.653918
dtype: float64

In [299]:
stacked.unstack()

                     A         B
first second
bar   one    -1.427343  0.434162
      two    -1.095679  0.028600
baz   one     1.692814  0.028645
      two     0.403866 -0.460692
foo   one    -0.751738  0.450839
      two    -0.689729  0.712863
qux   one    -0.667461 -0.240495
      two     0.173548 -0.653918

In [300]:
#Pivot

df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
    }
)

In [301]:
df

        A  B    C         D         E
0     one  A  foo -0.138592  1.653780
1     one  B  foo -0.282566 -1.521557
2     two  C  foo -0.132495 -1.271599
3   three  A  bar -0.955105 -0.629042
4     one  B  bar  0.057314 -1.592082
5     one  C  bar  0.935087 -0.753788
6     two  A  foo -0.854756 -0.062153
7   three  B  foo -0.078303 -2.360838
8     one  C  foo -0.995700 -0.176223
9     one  A  bar -1.795808  1.315276
10    two  B  bar -0.757946  0.012604
11  three  C  bar -0.337757 -0.810788

In [303]:
pd.pivot_table(df, values="D", index = ["A", "B"], columns=["C"])

C             bar       foo
A     B
one   A -1.795808 -0.138592
      B  0.057314 -0.282566
      C  0.935087 -0.995700
three A -0.955105       NaN
      B       NaN -0.078303
      C -0.337757       NaN
two   A       NaN -0.854756
      B -0.757946       NaN
      C       NaN -0.132495

In [307]:
#Categoricals

df = pd.DataFrame(
    {"id": [1, 2, 3, 4, 5, 6], "raw_grade": ["a", "b", "b", "a", "a", "e"]}
)
df

   id raw_grade
0   1         a
1   2         b
2   3         b
3   4         a
4   5         a
5   6         e

In [308]:
df["grade"] =  df["raw_grade"].astype("category")
df["grade"]

0    a
1    b
2    b
3    a
4    a
5    e
Name: grade, dtype: category
Categories (3, object): ['a', 'b', 'e']